#!/usr/bin/env bash
# A Bash script that displays a list of all running processes in a user-oriented format,
# including processes without TTY and showing process hierarchy

ps -eo user,pid,ppid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
