#!/usr/bin/env bash
# A Bash script to stop the 4-to_infinity_and_beyond process without using kill or killall

pid=$(pgrep 4-to_infinity_and_beyond)

if [ -n "$pid" ]; then
  perl -e "kill 15, $pid"
fi

exit 2
