#!/usr/bin/env bash
# A Bash script that loops printing "To infinity and beyond" and traps SIGTERM to print "I am invincible!!!"

term_handler() {
  printf "I am invincible!!!\n"
}

trap 'term_handler' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
